[package]
name = "doc_index_gen"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "doc-index-gen"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"

