[package]
name = "aivi"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo_metadata = "0.18.1"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
sha2 = "0.10.8"
toml = "0.8.20"
toml_edit = "0.22.27"

[dev-dependencies]
tempfile = "3.12.0"
