[package]
name = "aivi"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
wasm-encoder = "0.206.0"
wasmtime = "20.0.0"
wasmtime-wasi = "20.0.0"
